# Keep all in alphabetical order
components:
  hooks/open-telemetry:
    - Kavindu-Dodan
  hooks/validator:
    - Kavindu-Dodan
    - toddbaert
  providers/configcat:
    - rcrowe
    - z4kn4fein
  providers/flagd:
    - bacherfl
    - Kavindu-Dodan
    - toddbaert
  providers/flagsmith:
    - gagantrivedi
    - matthewelwell
  providers/flipt:
    - markphelps
  providers/from-env:
    - Kavindu-Dodan
    - toddbaert
  providers/go-feature-flag:
    - thomaspoignant
  providers/launchdarkly:
    - c4milo
    - kinyoklion
  providers/unleash:
    - liran2000
    - sighphyre
  providers/harness:
    - liran2000
    - davejohnston
  providers/statsig:
    - liran2000

ignored-authors:
  - renovate-bot
