// Code generated by mockery. DO NOT EDIT.

package flipt

import (
	context "context"

	evaluation "go.flipt.io/flipt/rpc/flipt/evaluation"

	mock "github.com/stretchr/testify/mock"

	rpcflipt "go.flipt.io/flipt/rpc/flipt"
)

// mockService is an autogenerated mock type for the Service type
type mockService struct {
	mock.Mock
}

type mockService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockService) EXPECT() *mockService_Expecter {
	return &mockService_Expecter{mock: &_m.Mock}
}

// Boolean provides a mock function with given fields: ctx, namespaceKey, flagKey, evalCtx
func (_m *mockService) Boolean(ctx context.Context, namespaceKey string, flagKey string, evalCtx map[string]interface{}) (*evaluation.BooleanEvaluationResponse, error) {
	ret := _m.Called(ctx, namespaceKey, flagKey, evalCtx)

	var r0 *evaluation.BooleanEvaluationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]interface{}) (*evaluation.BooleanEvaluationResponse, error)); ok {
		return rf(ctx, namespaceKey, flagKey, evalCtx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]interface{}) *evaluation.BooleanEvaluationResponse); ok {
		r0 = rf(ctx, namespaceKey, flagKey, evalCtx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*evaluation.BooleanEvaluationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, map[string]interface{}) error); ok {
		r1 = rf(ctx, namespaceKey, flagKey, evalCtx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockService_Boolean_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Boolean'
type mockService_Boolean_Call struct {
	*mock.Call
}

// Boolean is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceKey string
//   - flagKey string
//   - evalCtx map[string]interface{}
func (_e *mockService_Expecter) Boolean(ctx interface{}, namespaceKey interface{}, flagKey interface{}, evalCtx interface{}) *mockService_Boolean_Call {
	return &mockService_Boolean_Call{Call: _e.mock.On("Boolean", ctx, namespaceKey, flagKey, evalCtx)}
}

func (_c *mockService_Boolean_Call) Run(run func(ctx context.Context, namespaceKey string, flagKey string, evalCtx map[string]interface{})) *mockService_Boolean_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(map[string]interface{}))
	})
	return _c
}

func (_c *mockService_Boolean_Call) Return(_a0 *evaluation.BooleanEvaluationResponse, _a1 error) *mockService_Boolean_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockService_Boolean_Call) RunAndReturn(run func(context.Context, string, string, map[string]interface{}) (*evaluation.BooleanEvaluationResponse, error)) *mockService_Boolean_Call {
	_c.Call.Return(run)
	return _c
}

// Evaluate provides a mock function with given fields: ctx, namespaceKey, flagKey, evalCtx
func (_m *mockService) Evaluate(ctx context.Context, namespaceKey string, flagKey string, evalCtx map[string]interface{}) (*evaluation.VariantEvaluationResponse, error) {
	ret := _m.Called(ctx, namespaceKey, flagKey, evalCtx)

	var r0 *evaluation.VariantEvaluationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]interface{}) (*evaluation.VariantEvaluationResponse, error)); ok {
		return rf(ctx, namespaceKey, flagKey, evalCtx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]interface{}) *evaluation.VariantEvaluationResponse); ok {
		r0 = rf(ctx, namespaceKey, flagKey, evalCtx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*evaluation.VariantEvaluationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, map[string]interface{}) error); ok {
		r1 = rf(ctx, namespaceKey, flagKey, evalCtx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockService_Evaluate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Evaluate'
type mockService_Evaluate_Call struct {
	*mock.Call
}

// Evaluate is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceKey string
//   - flagKey string
//   - evalCtx map[string]interface{}
func (_e *mockService_Expecter) Evaluate(ctx interface{}, namespaceKey interface{}, flagKey interface{}, evalCtx interface{}) *mockService_Evaluate_Call {
	return &mockService_Evaluate_Call{Call: _e.mock.On("Evaluate", ctx, namespaceKey, flagKey, evalCtx)}
}

func (_c *mockService_Evaluate_Call) Run(run func(ctx context.Context, namespaceKey string, flagKey string, evalCtx map[string]interface{})) *mockService_Evaluate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(map[string]interface{}))
	})
	return _c
}

func (_c *mockService_Evaluate_Call) Return(_a0 *evaluation.VariantEvaluationResponse, _a1 error) *mockService_Evaluate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockService_Evaluate_Call) RunAndReturn(run func(context.Context, string, string, map[string]interface{}) (*evaluation.VariantEvaluationResponse, error)) *mockService_Evaluate_Call {
	_c.Call.Return(run)
	return _c
}

// GetFlag provides a mock function with given fields: ctx, namespaceKey, flagKey
func (_m *mockService) GetFlag(ctx context.Context, namespaceKey string, flagKey string) (*rpcflipt.Flag, error) {
	ret := _m.Called(ctx, namespaceKey, flagKey)

	var r0 *rpcflipt.Flag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*rpcflipt.Flag, error)); ok {
		return rf(ctx, namespaceKey, flagKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *rpcflipt.Flag); ok {
		r0 = rf(ctx, namespaceKey, flagKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpcflipt.Flag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceKey, flagKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockService_GetFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlag'
type mockService_GetFlag_Call struct {
	*mock.Call
}

// GetFlag is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceKey string
//   - flagKey string
func (_e *mockService_Expecter) GetFlag(ctx interface{}, namespaceKey interface{}, flagKey interface{}) *mockService_GetFlag_Call {
	return &mockService_GetFlag_Call{Call: _e.mock.On("GetFlag", ctx, namespaceKey, flagKey)}
}

func (_c *mockService_GetFlag_Call) Run(run func(ctx context.Context, namespaceKey string, flagKey string)) *mockService_GetFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *mockService_GetFlag_Call) Return(_a0 *rpcflipt.Flag, _a1 error) *mockService_GetFlag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockService_GetFlag_Call) RunAndReturn(run func(context.Context, string, string) (*rpcflipt.Flag, error)) *mockService_GetFlag_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTnewMockService interface {
	mock.TestingT
	Cleanup(func())
}

// newMockService creates a new instance of mockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockService(t mockConstructorTestingTnewMockService) *mockService {
	mock := &mockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
