// Code generated by mockery. DO NOT EDIT.

package flipt

import (
	context "context"

	evaluation "go.flipt.io/flipt/rpc/flipt/evaluation"

	mock "github.com/stretchr/testify/mock"
)

// mockService is an autogenerated mock type for the Service type
type mockService struct {
	mock.Mock
}

type mockService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockService) EXPECT() *mockService_Expecter {
	return &mockService_Expecter{mock: &_m.Mock}
}

// Boolean provides a mock function with given fields: ctx, environmentKey, namespaceKey, flagKey, evalCtx
func (_m *mockService) Boolean(ctx context.Context, environmentKey string, namespaceKey string, flagKey string, evalCtx map[string]interface{}) (*evaluation.BooleanEvaluationResponse, error) {
	ret := _m.Called(ctx, environmentKey, namespaceKey, flagKey, evalCtx)

	if len(ret) == 0 {
		panic("no return value specified for Boolean")
	}

	var r0 *evaluation.BooleanEvaluationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, map[string]interface{}) (*evaluation.BooleanEvaluationResponse, error)); ok {
		return rf(ctx, environmentKey, namespaceKey, flagKey, evalCtx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, map[string]interface{}) *evaluation.BooleanEvaluationResponse); ok {
		r0 = rf(ctx, environmentKey, namespaceKey, flagKey, evalCtx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*evaluation.BooleanEvaluationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, map[string]interface{}) error); ok {
		r1 = rf(ctx, environmentKey, namespaceKey, flagKey, evalCtx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockService_Boolean_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Boolean'
type mockService_Boolean_Call struct {
	*mock.Call
}

// Boolean is a helper method to define mock.On call
//   - ctx context.Context
//   - environmentKey string
//   - namespaceKey string
//   - flagKey string
//   - evalCtx map[string]interface{}
func (_e *mockService_Expecter) Boolean(ctx interface{}, environmentKey interface{}, namespaceKey interface{}, flagKey interface{}, evalCtx interface{}) *mockService_Boolean_Call {
	return &mockService_Boolean_Call{Call: _e.mock.On("Boolean", ctx, environmentKey, namespaceKey, flagKey, evalCtx)}
}

func (_c *mockService_Boolean_Call) Run(run func(ctx context.Context, environmentKey string, namespaceKey string, flagKey string, evalCtx map[string]interface{})) *mockService_Boolean_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(map[string]interface{}))
	})
	return _c
}

func (_c *mockService_Boolean_Call) Return(_a0 *evaluation.BooleanEvaluationResponse, _a1 error) *mockService_Boolean_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockService_Boolean_Call) RunAndReturn(run func(context.Context, string, string, string, map[string]interface{}) (*evaluation.BooleanEvaluationResponse, error)) *mockService_Boolean_Call {
	_c.Call.Return(run)
	return _c
}

// Variant provides a mock function with given fields: ctx, environmentKey, namespaceKey, flagKey, evalCtx
func (_m *mockService) Variant(ctx context.Context, environmentKey string, namespaceKey string, flagKey string, evalCtx map[string]interface{}) (*evaluation.VariantEvaluationResponse, error) {
	ret := _m.Called(ctx, environmentKey, namespaceKey, flagKey, evalCtx)

	if len(ret) == 0 {
		panic("no return value specified for Variant")
	}

	var r0 *evaluation.VariantEvaluationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, map[string]interface{}) (*evaluation.VariantEvaluationResponse, error)); ok {
		return rf(ctx, environmentKey, namespaceKey, flagKey, evalCtx)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, map[string]interface{}) *evaluation.VariantEvaluationResponse); ok {
		r0 = rf(ctx, environmentKey, namespaceKey, flagKey, evalCtx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*evaluation.VariantEvaluationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, map[string]interface{}) error); ok {
		r1 = rf(ctx, environmentKey, namespaceKey, flagKey, evalCtx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockService_Variant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Variant'
type mockService_Variant_Call struct {
	*mock.Call
}

// Variant is a helper method to define mock.On call
//   - ctx context.Context
//   - environmentKey string
//   - namespaceKey string
//   - flagKey string
//   - evalCtx map[string]interface{}
func (_e *mockService_Expecter) Variant(ctx interface{}, environmentKey interface{}, namespaceKey interface{}, flagKey interface{}, evalCtx interface{}) *mockService_Variant_Call {
	return &mockService_Variant_Call{Call: _e.mock.On("Variant", ctx, environmentKey, namespaceKey, flagKey, evalCtx)}
}

func (_c *mockService_Variant_Call) Run(run func(ctx context.Context, environmentKey string, namespaceKey string, flagKey string, evalCtx map[string]interface{})) *mockService_Variant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(map[string]interface{}))
	})
	return _c
}

func (_c *mockService_Variant_Call) Return(_a0 *evaluation.VariantEvaluationResponse, _a1 error) *mockService_Variant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockService_Variant_Call) RunAndReturn(run func(context.Context, string, string, string, map[string]interface{}) (*evaluation.VariantEvaluationResponse, error)) *mockService_Variant_Call {
	_c.Call.Return(run)
	return _c
}

// newMockService creates a new instance of mockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockService {
	mock := &mockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
