// Code generated by sync_assets.go. DO NOT EDIT.

package tck

// SpecRevision is the open-feature/spec commit the embedded conformance
// artifacts were taken from.
const SpecRevision = "dfa16586d91ca020ef1b3b82a7c972d833ff8f29"

// AssetsTree is the git tree object ID of specification/assets/provider-tck at
// SpecRevision.
//
// It identifies the artifacts rather than the commit, so an unrelated change
// elsewhere in the specification leaves it untouched, and
// `git rev-parse SpecRevision:specification/assets/provider-tck` reproduces it.
const AssetsTree = "904aa7d5fd7a856a4f92ace24355bd1987143abc"
