// Code generated by sync_assets.go. DO NOT EDIT.

package tck

// SpecRevision is the open-feature/spec commit the embedded conformance
// artifacts were taken from.
const SpecRevision = "dc4d7ae8df1c664f82a4adf46cd43812980c0da3"
