// Code generated by sync_assets.go. DO NOT EDIT.

package tck

// SpecRevision is the open-feature/spec commit the embedded conformance
// artifacts were taken from.
const SpecRevision = "dfa16586d91ca020ef1b3b82a7c972d833ff8f29"
