//go:build ignore

// Command sync_assets copies the conformance artifacts from the open-feature/spec
// submodule into the package, where they are committed and embedded.
//
// # Why the copies are committed
//
// They have to be, for Go specifically. A Go module is distributed as a zip built
// from the VCS tree, and a git submodule appears there only as a gitlink — its
// files are not in the tree. Embedding straight from the submodule works locally
// and in CI and then fails for anyone who runs `go get`, with the module shipping
// an empty directory and the package failing to compile. That is verifiable
// without publishing anything:
//
//	$ git archive HEAD tools/provider-tck | tar -t | grep 'pkg/tck/spec'
//	tools/provider-tck/pkg/tck/spec/
//	$ git archive HEAD tools/provider-tck | tar -t | grep -c '\.feature$'
//	0
//
// So the submodule stays the source of truth and records the spec revision, and
// the generated copies are what ships. The other languages do not need this: a
// wheel, a JAR and an npm package are all built from a working tree where the
// submodule is present.
//
// # Keeping them honest
//
// A committed generated file is a lie waiting to happen, so CI runs this and
// fails if the result differs from what is checked in. Editing the copies by hand
// is therefore caught, which is the property that matters — the whole point of a
// conformance suite is that its definition cannot drift.
//
// Usage:
//
//	go run ./sync_assets.go          # from tools/provider-tck
//	make provider-tck-assets         # from the repository root
package main

import (
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const (
	// specRoot is the checked-out submodule.
	specRoot = "pkg/tck/spec"

	// assetsPathInSpec is where the artifacts live inside the specification
	// repository. It names both the directory to copy from and the tree whose
	// hash is recorded alongside the commit.
	assetsPathInSpec = "specification/assets/provider-tck"

	destRoot = "pkg/tck/assets"
)

// specAssets is the directory the artifacts are copied from.
var specAssets = filepath.Join(specRoot, filepath.FromSlash(assetsPathInSpec))

// copies maps a directory in the spec repository to its destination in the
// package. The layout is preserved rather than renamed, so a reader comparing the
// two trees sees the same shape.
var copies = []string{"gherkin", "flags", "openapi"}

func main() {
	if _, err := os.Stat(specAssets); err != nil {
		fail("the spec submodule is not checked out at %s: %v\n\n"+
			"Run: git submodule update --init tools/provider-tck/pkg/tck/spec", specAssets, err)
	}

	if err := os.RemoveAll(destRoot); err != nil {
		fail("could not clear %s: %v", destRoot, err)
	}

	if err := writeGitattributes(); err != nil {
		fail("writing .gitattributes: %v", err)
	}

	total := 0
	for _, dir := range copies {
		n, err := copyTree(filepath.Join(specAssets, dir), filepath.Join(destRoot, dir))
		if err != nil {
			fail("copying %s: %v", dir, err)
		}
		total += n
	}

	if err := writeRevision(); err != nil {
		fail("recording the spec revision: %v", err)
	}

	fmt.Printf("synced %d conformance artifacts from %s\n", total, specAssets)
}

// gitattributes pins the line endings of everything generated here.
//
// It is written by the generator rather than placed beside it by hand, because
// this whole directory is wiped and rebuilt on every sync -- a hand-placed file
// would silently disappear on the next run, which is exactly what happened the
// first time.
//
// Without it, a fresh clone on Windows checks the artifacts out as CRLF (the
// core.autocrlf default), the generator writes LF, and the sync check reports a
// diff on a tree nobody touched. It also keeps the embedded bytes identical to
// every other language's copy.
const gitattributes = `# Generated by sync_assets.go from the open-feature/spec submodule. Do not edit.
#
# Line endings are pinned so a checkout on Windows does not convert them: the
# generator writes LF, so a CRLF working tree would make
# ` + "`make provider-tck-assets-check`" + ` report a spurious diff, and the embedded
# bytes would differ from every other language's copy of the same artifacts.
*.feature text eol=lf
*.json    text eol=lf
*.yaml    text eol=lf
`

func writeGitattributes() error {
	if err := os.MkdirAll(destRoot, 0o755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(destRoot, ".gitattributes"), []byte(gitattributes), 0o644)
}

func copyTree(src, dst string) (int, error) {
	count := 0
	err := filepath.WalkDir(src, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)

		if entry.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		// The spec repo carries a README and a .gitattributes alongside the
		// artifacts; neither is an artifact, and embedding them would put
		// unrelated files in every consumer's binary.
		if filepath.Ext(path) != ".feature" && filepath.Ext(path) != ".json" && filepath.Ext(path) != ".yaml" {
			return nil
		}

		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if err := os.WriteFile(target, data, 0o644); err != nil {
			return err
		}
		count++
		return nil
	})
	return count, err
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "sync_assets: "+format+"\n", args...)
	os.Exit(1)
}

// writeRevision records which revision of the specification these artifacts came
// from, as Go source.
//
// A conformance report has to name the revision it ran against or two reports
// cannot be compared, and for Go the submodule is absent from the published
// module, so the answer is baked in at sync time rather than read at run time.
// Generating it from the same command that copies the artifacts is what keeps it
// honest: the CI check regenerates both and fails on any difference, so a
// revision that disagrees with the artifacts beside it cannot be committed.
//
// The tree hash is recorded as well as the commit because it identifies the
// artifacts alone. It does not change when an unrelated part of the
// specification does, so two runs that executed identical artifacts report the
// same value even when pinned to different commits. It is also checkable, since
// `git rev-parse <commit>:specification/assets/provider-tck` must reproduce it.
func writeRevision() error {
	commit, err := gitOutput("-C", specRoot, "rev-parse", "HEAD")
	if err != nil {
		return err
	}
	tree, err := gitOutput("-C", specRoot, "rev-parse", "HEAD:"+assetsPathInSpec)
	if err != nil {
		return err
	}

	return os.WriteFile(filepath.Join("pkg", "tck", "revision.go"),
		[]byte(fmt.Sprintf(revisionTemplate, commit, tree)), 0o644)
}

func gitOutput(args ...string) (string, error) {
	out, err := exec.Command("git", args...).Output()
	if err != nil {
		return "", fmt.Errorf("git %s: %w", strings.Join(args, " "), err)
	}
	return strings.TrimSpace(string(out)), nil
}

const revisionTemplate = `// Code generated by sync_assets.go. DO NOT EDIT.

package tck

// SpecRevision is the open-feature/spec commit the embedded conformance
// artifacts were taken from.
const SpecRevision = %q

// AssetsTree is the git tree object ID of specification/assets/provider-tck at
// SpecRevision.
//
// It identifies the artifacts rather than the commit, so an unrelated change
// elsewhere in the specification leaves it untouched, and
// ` + "`git rev-parse SpecRevision:specification/assets/provider-tck`" + ` reproduces it.
const AssetsTree = %q
`
